print ('===============DESAFIO 01===============')
input()
nome = input ('qual é o seu nome?')
print ('Olá' ,nome, 'está tudo bem?')
idade = input ('Quantos anos você tem?')
print ('nossa, não sabia que você tinha',idade,'anos de idade')
input ()
print ('===============DESAFIO 02===============')
input ()
Dia = input ('Mas você nasceu em que dia?')
Mês = input ('E em que mês?')
Ano = input ('E o ano?')
print ('certo, então você nasceu',Dia, 'de',Mês,'de',Ano,'?')
input()
print ('===============DESAFIO 03===============')
n1 = int(input ('digite um numero'))
n2 = int(input ('digite outro'))
r = n1+n2
print ('A soma vale', r)
